apiVersion: v1
kind: Secret
metadata:
  name: longhorn-azblob-secret
  namespace: longhorn-system
type: Opaque
stringData:
  AZBLOB_ACCOUNT_NAME: ENC[AES256_GCM,data:zJTA25jfxekEeA==,iv:1LvNxIwHycDM4VNgunFEg3M+syPYXd1/gxgl4eI88xM=,tag:umrx8Gqj26IjT8Em5+iOXA==,type:str]
  AZBLOB_ACCOUNT_KEY: ENC[AES256_GCM,data:mGKwfwLEFJ78O1EVp5XM6DHMiimPe7YsAu+AZeReNXae7UIB/nTQwr3n93g6+5gfBLMaGxf23VaIC24NmbstfaIRu3MS3ZrdPDpO1EFiglt0O72WZlYC5Q==,iv:LiHTj7B+9oD2EDixV7lk37xJu8zkMaYa9PbTRqNjGY4=,tag:XclT12VuEgHG6zHOyAjiOA==,type:str]
sops:
  age:
    - recipient: age1wqmrjqvd55mqqesrq04ehf3rxnj7l6fvlz4en54mypkjq6urm39qv7lkep
      enc: |
          -----BEGIN AGE ENCRYPTED FILE-----
          YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtQzU4NGRyWDVMV0VFWWIz
          bndOWDN5aUluZHgwNWpuQm1vOWVkMTIyUjB3CkFkRGFIczBNREVzZ2xtM0ZvQlJh
          ZWZvNnIwdnBwRDhqYTRPSUMvQmI3K28KLS0tIFRZaFBIbFozemtVaWdXVC9MdzMy
          dXA3TERTMEkybGFONEIxVTM1NlMwTkEKpE0pDIX61yC8LiEhMgh1/2PP2ogfwfFb
          DF1dmqNftAHduBLO31ilNB0Jc9t3Mc5qCRNATkTI9ifd8KRorEsXwA==
          -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-19T14:53:43Z"
  mac: ENC[AES256_GCM,data:PJozBsXANjpQmFn34ShdF4ppi4VXJfeKwKuNzOL5W/eWqIj3TKL53D3+B+PNF7ilpn5e8G/1HKNSvPQs6EEG9W4YUsCNR3zZrSKmp0NmvauzG1ecLU3r6P2iayWoC5eWYVuoA4YgH3Oq6o2UP/Yh0zv7wy8YjSB3xRw0uPXf/R0=,iv:lI31ot7ltynfiGPDhL5Ps+QLdEb6ezQXJpOq7RIgomM=,tag:sQw/3pwhh/rCdo4YY6ZzBQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
