apiVersion: constraints.gatekeeper.sh/v1beta1
kind: RootPrevention
metadata:
  name: enforce-root-prevention
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
      - apiGroups: ["apps"]
        kinds: ["Deployment"]
    namespaces: ["default", "production", "staging", "engineering-platform"]
  parameters:
    exemptNamespaces:
      - "kube-system"
      - "kube-public"
      - "gatekeeper-system"
    exemptImages:
      - "registry.k8s.io/"
      - "gcr.io/distroless/"
    exemptUsers:
      - "1000"
      - "65534"
