apiVersion: v1
kind: Secret
metadata:
    name: keycloak-postgres-credentials
    namespace: keycloak
type: Opaque
stringData:
    POSTGRES_DB: ENC[AES256_GCM,data:1GLAwMXMeiM=,iv:qtUckRs2Rj0KHxaWP26IEu5ee6zj6IWJ+GCETFUU4+0=,tag:hx5wzhmPrnmctoUGCfyiPw==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:pVmSrsET/VY=,iv:dGhfFq0wasbpMe9my1+laePzciLDws8tnlNskAoUWSU=,tag:xudG/pa8vb27npnecYx5FQ==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:aklXZLVP2fw=,iv:/6pWi+O0VFXPYJ2T6Ht0sbLW4DSKGIUQQEAah78ULvQ=,tag:3+ec7+H661j0HPXkuGd4lQ==,type:str]
sops:
    age:
        - recipient: age1wqmrjqvd55mqqesrq04ehf3rxnj7l6fvlz4en54mypkjq6urm39qv7lkep
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSRFdrZVByN3U3akFUN2p0
            MnhvNnJpWkFCaGZ1amNobW94Sk1EbHV0SWtFClpXbnVUWE5tV3RxbEtwdlN1UjY2
            SHQvTHlQdUhkM1lxWVkxOHJqVzBzaVUKLS0tIEZ6S3ZjbDZzYkVsVWlwRmQzUldC
            eno2dExXQWloV2JuSUFxYk13Wk8vb1EK+JtJMMKxc08dNgqw1jh/wWBOXwTBIHhZ
            xG3ihoQx7sAL2++7QdR2tcmjY95nM1xyH/q5jMbxDshs6nmJqB8Rbw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-06T12:42:38Z"
    mac: ENC[AES256_GCM,data:3SjfbBC+apB4yjioRzzoMm8fe+TLqhTrpLJaYF2GmrKZK1UYppdw+QEBcKeGec3AkaUvkUkeL55PGc+6VSz8gvN+R563JAVSQ487FgNMj17v2WHhNZurCsbJ++zTAQKY3i5MEKdOo0PdyeDlhjOxvT9rGw/7y2/097bxBd4qk6o=,iv:SelwqzbkLA3mczUO4Ue0oJ5d7+NfPmbK4RMNiOcFLvw=,tag:VKx2SalMgdOfVSjp0O+Sxg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
