apiVersion: v1
kind: Secret
metadata:
    name: keycloak-credentials
    namespace: keycloak
type: Opaque
stringData:
    KEYCLOAK_ADMIN: ENC[AES256_GCM,data:sjsOWIg=,iv:6wyWyNo+tg+RosvzwnB5hIiU+PI0gkZeUNamzu+R4R4=,tag:f1HI/JbJX5KJMAaQkJGqiw==,type:str]
    KEYCLOAK_ADMIN_PASSWORD: ENC[AES256_GCM,data:QlhVz1Q=,iv:fce5hC9K8JcxzrZu83jOIwggpMa51SGEKw17QOwMSdo=,tag:Znqaj0UhgwAAEdt2N6pvpA==,type:str]
    KC_DB_USERNAME: ENC[AES256_GCM,data:gCxCGbToB7U=,iv:e2uFZjFemvGxAq90eUv5bgztOUy9QDfFXFU7GSCz3lc=,tag:8B9lp//x+aitUAHp42uZpQ==,type:str]
    KC_DB_PASSWORD: ENC[AES256_GCM,data:yHTkus2trac=,iv:rXR70YU+gWtjjbB82UgAepqYQehikymEKECXXRq/3fE=,tag:2tXtxnO9IFZqkmuL1i/5Uw==,type:str]
sops:
    age:
        - recipient: age1wqmrjqvd55mqqesrq04ehf3rxnj7l6fvlz4en54mypkjq6urm39qv7lkep
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6S1ZRREtpU21sbitlOVdN
            RlNEZGZualJMYjQzZHk5Ry9NVTNoYUo0cGdBCjBxQ25YTlViVnZmVFgxSm4xSXBX
            QXNiTGhDaXhOaUEwbGFuOVprT3J5RncKLS0tIHRvNXZlK1ovSWNydCtFNVBCaUdq
            UlR6Z0oveW9zeklMZi9OaU90d00wMkkKV+tbLTMeCer0MLD901GMcAn2GKkzTNke
            Px6oi2UHgSmubk8JgN6syVhi5OUEpx/pY/UjrimIhVZuDBfXQmwQlA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-06T12:42:28Z"
    mac: ENC[AES256_GCM,data:0vTTVUWmLI0C0GYeuQ5g9I866z7xF4Tbtpaxv9pOpZsU7n+j9Qcqg+W53LqPuu5jjkCXNH+cTDVC1VuAzeUGhlRVZpB6E50X+liS+hMNwlTnqYmrOkyGU8ZQyXI/ZhNTdrdTAJoR6eVMbXN8CzefVnBDRg2lxq1lq4ywzf0Po0I=,iv:43XgWF2NFmxKGAOxsNHxjomkz1MMxdcyx5qscVz32bw=,tag:8sEB/qJaBOdsnwT2lnNt6g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
