apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: cors
  namespace: keycloak
spec:
  headers:
    accessControlAllowCredentials: true
    accessControlAllowHeaders:
      - Authorization
      - Content-Type
      - Accept
      - Origin
      - X-Requested-With
    accessControlAllowMethods:
      - GET
      - POST
      - PUT
      - DELETE
      - OPTIONS
      - HEAD
      - PATCH
    accessControlAllowOriginList:
      - http://localhost:4200
      - https://kc.kube-playground.io
      - https://teams-ui.kube-playground.io
    accessControlExposeHeaders:
      - Location
    accessControlMaxAge: 3600
