apiVersion: v1
kind: Secret
metadata:
  name: keycloak-postgres-credentials
  namespace: keycloak
type: Opaque
# TODO: Encrypt with SOPS before committing production values
# sops --encrypt --age <age-public-key> --encrypted-regex '^(data|stringData)$' --in-place keycloak-postgres-secrets.yaml
stringData:
  POSTGRES_DB: keycloak
  POSTGRES_PASSWORD: keycloak
  POSTGRES_USER: keycloak
