kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
resources:
  - keycloak-cors-middleware.yaml
  - keycloak-deployment.yaml
  - keycloak-ingress.yaml
  - keycloak-postgres-deployment.yaml
  - keycloak-postgres-secrets.yaml
  - keycloak-postgres-service.yaml
  - keycloak-realm-config.yaml
  - keycloak-secrets.yaml
  - keycloak-service.yaml
  - namespace.yaml
