apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./ingress.yaml
  - ./namespace.yaml
  - ./teams-api-deployment.yaml
  - ./teams-api-service.yaml
  - ./teams-ui-deployment.yaml
  - ./teams-ui-service.yaml