apiVersion: v1
kind: Secret
metadata:
    name: scaffold-github-credentials
stringData:
    GITHUB_REPO: ENC[AES256_GCM,data:h2EMCJfVQyYB0mM=,iv:EXKeLp2oMN5FYgS4V4iNrMpRLrXjjwIYWUPXj3ilhuA=,tag:0879s0b1bx8P7L52G24AYg==,type:str]
    GITHUB_TOKEN: ENC[AES256_GCM,data:N498z0BavhtYICiCBJzVCqq34zCBiAMIPHIV8D0CpbP3QxGYXN2dWiM7bzsnBz8hofHdrbIEs4bExwh3bhskM2AKYu8B0EogjJlUgFnVo2Hofu3EjdDYGQeG0/Qk,iv:ejKEUm3SdYGLg6GdqOPWQDoETLS4+mqkTivsDNUKL2M=,tag:G4tH+ZDU3IEDfCuykrsvUA==,type:str]
type: Opaque
sops:
    age:
        - recipient: age1wqmrjqvd55mqqesrq04ehf3rxnj7l6fvlz4en54mypkjq6urm39qv7lkep
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhTFNKdk5ZVDJodjNGMjFi
            VUhPaXlGaldSTUljUUZ3MDdoSkJQRXNpRXljCkVaOHNESS94M3lXSDRSWjFUeDB2
            ZWF3aGdPVVJ0cE1qWmp6RER1N3pFcGcKLS0tICtnTnlmTERsUEM2ZGwwSEk3WjlE
            eHdnL1JLckZIdlU3akkzYWdYbnhtTjAKyH5f2eHYfkl2PzJHMTTz6xBz49Z+SH+f
            VloSabGvW3x4aUG0pybcj63/L41SU8haVH88K1bAPGtolrjKP7T+zw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-10T21:07:57Z"
    mac: ENC[AES256_GCM,data:5gnbOTqWemYUJdVVBJ1fxKKcXUFx/Y6iQ46WHQwn9QGWX2cEag1Y/ALf0gI63sp9B5M2v/ZZ7IzCW9OrnbfY2RrhcqT/LX0oh7TEkOfKqlGLuOIHGPbjIedcbNM0sTXtCuViy5qNv3nUG4t31gmchB8Bmma7phjsjZAimTRaKLk=,iv:GQL5n1jHZxNoeKsmV0FpILzngS1PX3B60ehUOWgECOg=,tag:A71etVlKqW3ACrJccgN95Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
