apiVersion: v1
kind: Secret
metadata:
    name: scaffold-github-credentials
stringData:
    GITHUB_REPO: ENC[AES256_GCM,data:4qItLmnlCdaFluA=,iv:LyUWZNYupK83SB5lMQ0idF7t6Mvvod7wCyzrfzrupA4=,tag:/x4qoWLDxqozPQH3om2oFA==,type:str]
    GITHUB_TOKEN: ENC[AES256_GCM,data:ujIrrvm42bYlhTORifWM3tFa4myITxh8UDuasweRF+vUUndhF4CH5jWOSfIDCtkpofv35oUvvmfqbF8UGAe5oRy6UllfB5plZqAf9B/11G2b5CTs+BjWZgVElDpb,iv:Y83kEip6u7ztxZ6b4FlSgLCbIh5Xb55nWJ1htYNG/GU=,tag:O53R3uEk3oq19cW/AxDRdQ==,type:str]
type: Opaque
sops:
    age:
        - recipient: age1wqmrjqvd55mqqesrq04ehf3rxnj7l6fvlz4en54mypkjq6urm39qv7lkep
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFWnhGbGY1L1lkNWQzUnN0
            TmQrZnBFazB6ejFHZ1dtTHlZMW9JWXdXb0hBCmhPNGN3UzFBSnRIMHJyeElzSGJ4
            dVdvY0QrQlJkQkdLTGJqQnplaXFtbUEKLS0tIENJOWRFdXZoTkJGTjBaWVo1alZp
            VkJ2ejVRa2dJblRMV1NiWC94UTNmMTgK5+KUjupoNSXvjlGCYdoGsPqZM+v6U9Nq
            /dLZvERI+GxQOl/iohoH1YRXBhSymiudRZQv8wlWYaK77GFlwWYU6w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-10T20:25:40Z"
    mac: ENC[AES256_GCM,data:5D+7HaDhKj/WMABWoGP1xneTfyMfdWkmv99RSNnCJvtt/DcKBiJYflpZOXWeZ3qXzw4+1BUdk05Ya9Z16Fg12P1zKg+qNvSIHBpGQ9Zo6qaNqmw//rQRYA8KQt1LRgRBqpwFQ/yOcmCyO96xJ2dELHlVHaV6swjZrzRCMa508Nk=,iv:tSzR90jtMNXM3+YZbGxYCLchFKOkoj5WRbhHRD0SMRc=,tag:me3bGdoZUxKolw57wK8dPQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
