apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: falco
spec:
  interval: 30m
  chart:
    spec:
      chart: falco
      version: "8.0.1"
      sourceRef:
        kind: HelmRepository
        name: falcosecurity
      interval: 12h
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  driftDetection:
    mode: enabled
    ignore: []
  valuesFrom:
    - kind: ConfigMap
      name: falco-custom-rules
      valuesKey: custom-rules-values.yaml
  values:
    driver:
      kind: modern_ebpf
    falcosidekick:
      enabled: true
    falcoctl:
      artifact:
        install:
          enabled: true
          args: ["--log-format=json"]
          resources: {}
          securityContext: {}
          mounts:
            volumeMounts: []
        follow:
          enabled: true
          env: []
          envFrom: []
          args: ["--log-format=json"]
          resources: {}
          securityContext: {}
          mounts:
            volumeMounts: []
      # -- Configuration file of the falcoctl tool. It is saved in a configmap and mounted on the falcotl containers.
      config:
        # -- List of indexes that falcoctl downloads and uses to locate and download artiafcts. For more info see:
        # https://github.com/falcosecurity/falcoctl/blob/main/proposals/20220916-rules-and-plugin-distribution.md#index-file-overview
        indexes:
          - name: falcosecurity
            url: https://falcosecurity.github.io/falcoctl/index.yaml
        artifact:
          allowedTypes:
            - rulesfile
            - plugin
          install:
            resolveDeps: true
            refs: [falco-rules:5]
            rulesfilesDir: /rulesfiles
            pluginsDir: /plugins
            stateDir: /artifactstate
          follow:
            refs: [falco-rules:5]
            every: 168h
            falcoversions: http://localhost:8765/versions
            rulesfilesDir: /rulesfiles
            pluginsDir: /plugins
            stateDir: /artifactstate
    webserver:
      prometheus_metrics_enabled: true
    metrics:
      enabled: false
      interval: 1h
      # Typically, in production, you only use `output_rule` or `output_file`, but not both. 
      # However, if you have a very unique use case, you can use both together.
      # Set `webserver.prometheus_metrics_enabled` for Prometheus output.
      output_rule: true
      # output_file: /tmp/falco_stats.jsonl
      rules_counters_enabled: true
      resource_utilization_enabled: true
      state_counters_enabled: true
      kernel_event_counters_enabled: true
      # Enabling `kernel_event_counters_per_cpu_enabled` automatically enables `kernel_event_counters_enabled`
      kernel_event_counters_per_cpu_enabled: false
      libbpf_stats_enabled: true
      plugins_metrics_enabled: true
      jemalloc_stats_enabled: false
      convert_memory_to_mb: true
      include_empty_values: false
    serviceMonitor:
      create: true
      path: /metrics
      # If your Prometheus deployment is configured to use serviceMonitorSelector, then add the right
      # label here in order for the ServiceMonitor to be selected for target discovery.
      labels: {}
      # -- selector set of labels that should match the labels on the Service targeted by the current serviceMonitor.
      selector: {}
      # -- interval specifies the time interval at which Prometheus should scrape metrics from the service.
      interval: 15s
      # -- scheme specifies network protocol used by the metrics endpoint. In this case HTTP.
      scheme: http
      # -- tlsConfig specifies TLS (Transport Layer Security) configuration for secure communication when
      # scraping metrics from a service. It allows you to define the details of the TLS connection, such as
      # CA certificate, client certificate, and client key. Currently, the k8s-metacollector does not support
      # TLS configuration for the metrics endpoint.
      tlsConfig: {}
        # insecureSkipVerify: false
        # caFile: /path/to/ca.crt
        # certFile: /path/to/client.crt
      # keyFile: /path/to/client.key
      # -- scrapeTimeout determines the maximum time Prometheus should wait for a target to respond to a scrape request.
      # If the target does not respond within the specified timeout, Prometheus considers the scrape as failed for
      # that target.
      scrapeTimeout: 10s
      # -- relabelings configures the relabeling rules to apply the target's metadata labels.
      relabelings: []
      # -- targetLabels defines the labels which are transferred from the associated Kubernetes service object onto the ingested metrics.
      targetLabels: []
      # -- endpointPort is the port in the Falco service that exposes the metrics service. Change the value if you deploy a custom service
      # for Falco's metrics.
      endpointPort: "metrics"