apiVersion: v1
data:
  admin-secret: ENC[AES256_GCM,data:rF1oBORNohWJTY/1v1z5DfiytWcQQw2U,iv:v5dxyT73NBuoyz3i+ZTgF9uLxj/SFEosReo/hysdEvo=,tag:NEM4U2i3UqsBuKhaFZe9JA==,type:str]
  admin-user: ENC[AES256_GCM,data:XLv9flcKM1g=,iv:sC25Tqwc6ScUrP6h0EFsFjQzJpvyhOtsOvdXIrzRaYg=,tag:zxT2efWMkx/pj7O20AaW/g==,type:str]
kind: Secret
metadata:
  name: grafana-admin-credentials
sops:
  age:
    - recipient: age1wqmrjqvd55mqqesrq04ehf3rxnj7l6fvlz4en54mypkjq6urm39qv7lkep
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJQWI1ZXpKM1RaZGRkK2tw
        Ty9qZGtXQ2VhSHpxT05ZcHMvZ3RrUzNScEVZCmFiSG1uTERYbDRESlIzOWpNck5I
        TmtRRWJXWUlsanBVckQ0N2pWY3htdUUKLS0tIHlDSXcyZk1oajJBOXJabm1FSGM2
        UVlCL1hSeko2cWxQRDhDaGxkc1RrdVkKR4PiikeGx0Vi0wzS+xHMxHZuqbAEqzGu
        0HddKGJsgAENuukOFXr18OFSCtRB6R0hCcpdGyxZqnMQffywTkG5fg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-10T19:16:10Z"
  mac: ENC[AES256_GCM,data:bUXfJsP5tGSr86crLQFPVFyFQxHmFVgbOhh3BP/ydTal5Thaa0vYJZUd7gXNZ0xOYG+JJFBkUr+EjZvuis8HoTwH+pH8aMCMbmiaj0pgT1Fsy0/0o4IKJptnnlaJkKYf/NWMdn1vxvWN26PCqDjsRZV/S5tHfvoR5xcH+TNLAPE=,iv:CnVZ9YXs8QVTm1oFRKdMIueqKAucuzPFQO/Pgi5Dhm8=,tag:mPsTqPx7DWQozoUu31xr9A==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
